import type { Meal, WeeklyMeals } from "@/types/meal";

export const mockMeals: { [key: string]: Meal } = {
  "greek-yogurt-bowl": {
    id: "greek-yogurt-bowl",
    name: "Greek Yogurt Berry Bowl",
    description: "Creamy Greek yogurt topped with fresh berries, granola, and honey",
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    category: "breakfast",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    ingredients: [
      { name: "Greek yogurt", amount: "1 cup", category: "fridge" },
      { name: "Mixed berries", amount: "1/2 cup", category: "fridge" },
      { name: "Granola", amount: "1/4 cup", category: "cupboard" },
      { name: "Honey", amount: "1 tbsp", category: "cupboard" },
    ],
    instructions: [
      "Add Greek yogurt to a bowl",
      "Top with mixed berries",
      "Sprinkle granola on top",
      "Drizzle with honey",
      "Serve immediately",
    ],
    nutrition: { calories: 320, protein: 18, carbs: 45, fat: 8 },
  },
  "avocado-toast": {
    id: "avocado-toast",
    name: "Avocado Toast with Poached Egg",
    description: "Toasted sourdough with mashed avocado and a perfectly poached egg",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&q=80",
    category: "breakfast",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    ingredients: [
      { name: "Sourdough bread", amount: "2 slices", category: "cupboard" },
      { name: "Avocado", amount: "1", category: "fridge" },
      { name: "Egg", amount: "1", category: "fridge" },
      { name: "Salt", amount: "to taste", category: "cupboard" },
      { name: "Pepper", amount: "to taste", category: "cupboard" },
    ],
    instructions: [
      "Toast the sourdough bread until golden",
      "Mash the avocado with salt and pepper",
      "Poach the egg in simmering water for 3-4 minutes",
      "Spread avocado on toast",
      "Top with poached egg",
      "Season with additional salt and pepper",
    ],
    nutrition: { calories: 385, protein: 14, carbs: 32, fat: 24 },
  },
  "chicken-caesar-salad": {
    id: "chicken-caesar-salad",
    name: "Grilled Chicken Caesar Salad",
    description: "Classic Caesar salad with grilled chicken breast and homemade croutons",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80",
    category: "lunch",
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    ingredients: [
      { name: "Chicken breast", amount: "2", category: "fridge" },
      { name: "Romaine lettuce", amount: "1 head", category: "fridge" },
      { name: "Parmesan cheese", amount: "1/2 cup", category: "fridge" },
      { name: "Caesar dressing", amount: "1/4 cup", category: "fridge" },
      { name: "Croutons", amount: "1 cup", category: "cupboard" },
    ],
    instructions: [
      "Season and grill chicken breast for 6-7 minutes per side",
      "Chop romaine lettuce into bite-sized pieces",
      "Slice grilled chicken",
      "Toss lettuce with Caesar dressing",
      "Top with sliced chicken, croutons, and Parmesan",
      "Serve immediately",
    ],
    nutrition: { calories: 425, protein: 42, carbs: 18, fat: 22 },
  },
  "quinoa-bowl": {
    id: "quinoa-bowl",
    name: "Mediterranean Quinoa Bowl",
    description: "Nutritious quinoa bowl with roasted vegetables and tahini dressing",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
    category: "lunch",
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    ingredients: [
      { name: "Quinoa", amount: "1 cup", category: "cupboard" },
      { name: "Cherry tomatoes", amount: "1 cup", category: "fridge" },
      { name: "Cucumber", amount: "1", category: "fridge" },
      { name: "Chickpeas", amount: "1 can", category: "cupboard" },
      { name: "Tahini", amount: "2 tbsp", category: "cupboard" },
      { name: "Lemon juice", amount: "2 tbsp", category: "fridge" },
    ],
    instructions: [
      "Cook quinoa according to package instructions",
      "Roast chickpeas at 400°F for 20 minutes",
      "Chop vegetables",
      "Mix tahini with lemon juice and water for dressing",
      "Assemble bowl with quinoa, vegetables, and chickpeas",
      "Drizzle with tahini dressing",
    ],
    nutrition: { calories: 380, protein: 14, carbs: 52, fat: 14 },
  },
  "almonds-trail-mix": {
    id: "almonds-trail-mix",
    name: "Energy Trail Mix",
    description: "Homemade trail mix with almonds, dried fruits, and dark chocolate",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&q=80",
    category: "snack",
    prepTime: 5,
    cookTime: 0,
    servings: 4,
    ingredients: [
      { name: "Almonds", amount: "1 cup", category: "cupboard" },
      { name: "Dried cranberries", amount: "1/2 cup", category: "cupboard" },
      { name: "Dark chocolate chips", amount: "1/4 cup", category: "cupboard" },
      { name: "Pumpkin seeds", amount: "1/4 cup", category: "cupboard" },
    ],
    instructions: [
      "Mix all ingredients in a large bowl",
      "Store in an airtight container",
      "Portion into small bags for easy snacking",
    ],
    nutrition: { calories: 180, protein: 6, carbs: 18, fat: 11 },
  },
  "hummus-veggies": {
    id: "hummus-veggies",
    name: "Hummus & Veggie Sticks",
    description: "Fresh vegetable sticks with creamy homemade hummus",
    image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?w=800&q=80",
    category: "snack",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    ingredients: [
      { name: "Carrots", amount: "2", category: "fridge" },
      { name: "Celery", amount: "3 stalks", category: "fridge" },
      { name: "Bell pepper", amount: "1", category: "fridge" },
      { name: "Hummus", amount: "1 cup", category: "fridge" },
    ],
    instructions: [
      "Wash and cut vegetables into sticks",
      "Arrange on a plate",
      "Serve with hummus in the center",
    ],
    nutrition: { calories: 150, protein: 6, carbs: 20, fat: 6 },
  },
  "salmon-asparagus": {
    id: "salmon-asparagus",
    name: "Baked Salmon with Asparagus",
    description: "Herb-crusted salmon with roasted asparagus and lemon butter",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
    category: "dinner",
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    ingredients: [
      { name: "Salmon fillet", amount: "2", category: "fridge" },
      { name: "Asparagus", amount: "1 bunch", category: "fridge" },
      { name: "Olive oil", amount: "2 tbsp", category: "cupboard" },
      { name: "Lemon", amount: "1", category: "fridge" },
      { name: "Garlic", amount: "2 cloves", category: "cupboard" },
      { name: "Butter", amount: "2 tbsp", category: "fridge" },
    ],
    instructions: [
      "Preheat oven to 400°F",
      "Season salmon with salt, pepper, and herbs",
      "Arrange asparagus on baking sheet with salmon",
      "Drizzle with olive oil",
      "Bake for 15-20 minutes",
      "Serve with lemon butter sauce",
    ],
    nutrition: { calories: 445, protein: 38, carbs: 8, fat: 30 },
  },
  "chicken-stir-fry": {
    id: "chicken-stir-fry",
    name: "Teriyaki Chicken Stir-Fry",
    description: "Quick and healthy stir-fry with chicken and colorful vegetables",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&q=80",
    category: "dinner",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    ingredients: [
      { name: "Chicken breast", amount: "1 lb", category: "fridge" },
      { name: "Broccoli", amount: "2 cups", category: "fridge" },
      { name: "Bell peppers", amount: "2", category: "fridge" },
      { name: "Teriyaki sauce", amount: "1/2 cup", category: "cupboard" },
      { name: "Rice", amount: "2 cups cooked", category: "cupboard" },
      { name: "Sesame oil", amount: "1 tbsp", category: "cupboard" },
    ],
    instructions: [
      "Cut chicken into bite-sized pieces",
      "Chop vegetables",
      "Heat sesame oil in a large wok or skillet",
      "Cook chicken until golden",
      "Add vegetables and stir-fry for 5 minutes",
      "Add teriyaki sauce and simmer",
      "Serve over rice",
    ],
    nutrition: { calories: 420, protein: 35, carbs: 48, fat: 10 },
  },
  "beef-tacos": {
    id: "beef-tacos",
    name: "Spicy Beef Tacos",
    description: "Seasoned ground beef tacos with fresh toppings",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&q=80",
    category: "dinner",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    ingredients: [
      { name: "Ground beef", amount: "1 lb", category: "fridge" },
      { name: "Taco shells", amount: "8", category: "cupboard" },
      { name: "Lettuce", amount: "2 cups shredded", category: "fridge" },
      { name: "Tomatoes", amount: "2", category: "fridge" },
      { name: "Cheese", amount: "1 cup shredded", category: "fridge" },
      { name: "Sour cream", amount: "1/2 cup", category: "fridge" },
      { name: "Taco seasoning", amount: "1 packet", category: "cupboard" },
    ],
    instructions: [
      "Brown ground beef in a skillet",
      "Add taco seasoning and water, simmer for 5 minutes",
      "Warm taco shells in oven",
      "Chop lettuce and tomatoes",
      "Assemble tacos with beef and toppings",
      "Serve immediately",
    ],
    nutrition: { calories: 485, protein: 28, carbs: 32, fat: 26 },
  },
  "veggie-lasagna": {
    id: "veggie-lasagna",
    name: "Vegetable Lasagna",
    description: "Layered pasta with roasted vegetables and ricotta cheese",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&q=80",
    category: "dinner",
    prepTime: 30,
    cookTime: 45,
    servings: 8,
    ingredients: [
      { name: "Lasagna noodles", amount: "12", category: "cupboard" },
      { name: "Ricotta cheese", amount: "2 cups", category: "fridge" },
      { name: "Mozzarella cheese", amount: "2 cups", category: "fridge" },
      { name: "Spinach", amount: "2 cups", category: "fridge" },
      { name: "Zucchini", amount: "2", category: "fridge" },
      { name: "Marinara sauce", amount: "4 cups", category: "cupboard" },
    ],
    instructions: [
      "Preheat oven to 375°F",
      "Cook lasagna noodles according to package",
      "Sauté vegetables until tender",
      "Layer noodles, ricotta, vegetables, sauce, and mozzarella",
      "Repeat layers",
      "Cover with foil and bake for 30 minutes",
      "Remove foil and bake 15 more minutes",
      "Let rest before serving",
    ],
    nutrition: { calories: 380, protein: 22, carbs: 42, fat: 14 },
  },
};

// Generate current week meals
export const currentWeekMeals: WeeklyMeals = {
  Monday: {
    breakfast: mockMeals["greek-yogurt-bowl"],
    lunch: mockMeals["chicken-caesar-salad"],
    snack: mockMeals["almonds-trail-mix"],
    dinner: mockMeals["salmon-asparagus"],
  },
  Tuesday: {
    breakfast: mockMeals["avocado-toast"],
    lunch: mockMeals["quinoa-bowl"],
    snack: mockMeals["hummus-veggies"],
    dinner: mockMeals["chicken-stir-fry"],
  },
  Wednesday: {
    breakfast: mockMeals["greek-yogurt-bowl"],
    lunch: mockMeals["chicken-caesar-salad"],
    snack: mockMeals["almonds-trail-mix"],
    dinner: mockMeals["beef-tacos"],
  },
  Thursday: {
    breakfast: mockMeals["avocado-toast"],
    lunch: mockMeals["quinoa-bowl"],
    snack: mockMeals["hummus-veggies"],
    dinner: mockMeals["veggie-lasagna"],
  },
  Friday: {
    breakfast: mockMeals["greek-yogurt-bowl"],
    lunch: mockMeals["chicken-caesar-salad"],
    snack: mockMeals["almonds-trail-mix"],
    dinner: mockMeals["salmon-asparagus"],
  },
  Saturday: {
    breakfast: mockMeals["avocado-toast"],
    lunch: mockMeals["quinoa-bowl"],
    snack: mockMeals["hummus-veggies"],
    dinner: mockMeals["chicken-stir-fry"],
  },
  Sunday: {
    breakfast: mockMeals["greek-yogurt-bowl"],
    lunch: mockMeals["chicken-caesar-salad"],
    snack: mockMeals["almonds-trail-mix"],
    dinner: mockMeals["beef-tacos"],
  },
};

// Generate next week meals (slightly different)
export const nextWeekMeals: WeeklyMeals = {
  Monday: {
    breakfast: mockMeals["avocado-toast"],
    lunch: mockMeals["quinoa-bowl"],
    snack: mockMeals["hummus-veggies"],
    dinner: mockMeals["veggie-lasagna"],
  },
  Tuesday: {
    breakfast: mockMeals["greek-yogurt-bowl"],
    lunch: mockMeals["chicken-caesar-salad"],
    snack: mockMeals["almonds-trail-mix"],
    dinner: mockMeals["chicken-stir-fry"],
  },
  Wednesday: {
    breakfast: mockMeals["avocado-toast"],
    lunch: mockMeals["quinoa-bowl"],
    snack: mockMeals["hummus-veggies"],
    dinner: mockMeals["salmon-asparagus"],
  },
  Thursday: {
    breakfast: mockMeals["greek-yogurt-bowl"],
    lunch: mockMeals["chicken-caesar-salad"],
    snack: mockMeals["almonds-trail-mix"],
    dinner: mockMeals["beef-tacos"],
  },
  Friday: {
    breakfast: mockMeals["avocado-toast"],
    lunch: mockMeals["quinoa-bowl"],
    snack: mockMeals["hummus-veggies"],
    dinner: mockMeals["veggie-lasagna"],
  },
  Saturday: {
    breakfast: mockMeals["greek-yogurt-bowl"],
    lunch: mockMeals["chicken-caesar-salad"],
    snack: mockMeals["almonds-trail-mix"],
    dinner: mockMeals["salmon-asparagus"],
  },
  Sunday: {
    breakfast: mockMeals["avocado-toast"],
    lunch: mockMeals["quinoa-bowl"],
    snack: mockMeals["hummus-veggies"],
    dinner: mockMeals["chicken-stir-fry"],
  },
};

export const healthySnacks: Meal[] = [
  mockMeals["almonds-trail-mix"],
  mockMeals["hummus-veggies"],
  mockMeals["greek-yogurt-bowl"],
];

export const breakfastRecipes: Meal[] = [
  mockMeals["greek-yogurt-bowl"],
  mockMeals["avocado-toast"],
];

export const freezableDinners: Meal[] = [
  mockMeals["veggie-lasagna"],
  mockMeals["chicken-stir-fry"],
  mockMeals["beef-tacos"],
];